import '../models/content_models.dart';

/// Catálogo de confusiones. Cada distractor de la app declara cuál produce;
/// el diagnóstico acumula evidencia y enlaza el remedio.
const List<Confusion> confusions = [
  Confusion(
    id: 'una_corrida_es_verdad',
    name: 'Una corrida es «la» respuesta',
    description: 'Tratar el resultado de una sola simulación como el valor exacto, sin su margen de error.',
    remedy: 'Corre la misma simulación con cinco semillas y compara: cada corrida es una estimación con error.',
    remedyLessonId: 'l1_4',
    remedyExperimentId: 'e3_seeds',
  ),
  Confusion(
    id: 'error_lineal_n',
    name: 'El error baja en proporción a n',
    description: 'Creer que duplicar las iteraciones reduce el error a la mitad. El error baja con √n.',
    remedy: 'Compara réplicas con n = 400 y n = 1 600: con cuatro veces más iteraciones, el error solo se reduce a la mitad.',
    remedyLessonId: 'l3_3',
    remedyExperimentId: 'e12_sqrt_n',
  ),
  Confusion(
    id: 'mas_n_corrige_modelo',
    name: 'Más iteraciones corrigen un mal modelo',
    description: 'Pensar que una simulación que converge es correcta. Converge al valor del modelo, aunque el modelo esté mal.',
    remedy: 'Revisa la validación del modelo: entradas, supuestos y fórmula se comprueban aparte de la precisión.',
    remedyLessonId: 'l3_4',
  ),
  Confusion(
    id: 'pseudo_es_azar_real',
    name: 'El azar de la computadora es azar puro',
    description: 'Ignorar que los números son pseudoaleatorios: una regla determinista que parece azar y se repite con la misma semilla.',
    remedy: 'Genera números con la misma semilla dos veces y observa que la secuencia se repite exactamente.',
    remedyLessonId: 'l1_2',
    remedyExperimentId: 'e4_lcg',
  ),
  Confusion(
    id: 'histograma_prueba_calidad',
    name: 'Un histograma plano prueba un buen generador',
    description: 'Juzgar un generador solo por la uniformidad de sus valores, sin mirar si los consecutivos son independientes.',
    remedy: 'Dibuja los pares (uₖ, uₖ₊₁) del generador defectuoso: su histograma es plano y sus pares caen en rectas.',
    remedyLessonId: 'l1_2',
    remedyExperimentId: 'e4_lcg',
  ),
  Confusion(
    id: 'uniforme_directa',
    name: 'Escalar la uniforme sirve para todo',
    description: 'Obtener cualquier variable multiplicando o redondeando una uniforme, sin respetar sus probabilidades.',
    remedy: 'Construye un dado cargado partiendo [0, 1) en tramos del largo de cada probabilidad.',
    remedyLessonId: 'l1_3',
    remedyExperimentId: 'e6_discrete',
  ),
  Confusion(
    id: 'inversa_con_densidad',
    name: 'Invertir la densidad en vez de la acumulada',
    description: 'Aplicar la transformada inversa sobre f(x). La uniforme se proyecta sobre la acumulada F(x), que va de 0 a 1.',
    remedy: 'Sigue el recorrido u → F(x) → x en el laboratorio de la transformada inversa.',
    remedyLessonId: 'l1_3',
    remedyExperimentId: 'e5_inverse',
  ),
  Confusion(
    id: 'promedio_de_entradas',
    name: 'Falacia de los promedios',
    description: 'Suponer que poner cada entrada en su promedio da el resultado promedio. Falla cuando el modelo no es lineal (mínimos, máximos, umbrales).',
    remedy: 'Simula la planta con capacidad limitada: con la demanda media se planifican ventas que en promedio no ocurren.',
    remedyLessonId: 'l2_3',
    remedyExperimentId: 'e8_capacity',
  ),
  Confusion(
    id: 'mas_probable_es_esperado',
    name: 'El escenario más probable es el esperado',
    description: 'Usar los valores más probables (modas) como si fueran los esperados. Con entradas asimétricas no coinciden.',
    remedy: 'Compara el VAN del escenario más probable con el VAN medio de la simulación del proyecto.',
    remedyLessonId: 'l2_3',
    remedyExperimentId: 'e7_npv',
  ),
  Confusion(
    id: 'paralelo_sin_sesgo',
    name: 'Tareas en paralelo sin costo de espera',
    description: 'Planificar con la duración media de cada ruta paralela. El proyecto espera a la más lenta, y el máximo de promedios subestima el plazo.',
    remedy: 'Activa la segunda ruta en el laboratorio de plazos y mira caer la probabilidad de cumplir.',
    remedyLessonId: 'l2_3',
    remedyExperimentId: 'e9_merge',
  ),
  Confusion(
    id: 'ignorar_correlacion',
    name: 'Suponer independencia sin pensarlo',
    description: 'Simular entradas que se mueven juntas como si fueran independientes. Con correlación positiva el riesgo del total crece.',
    remedy: 'Mueve la correlación entre dos costos y observa el percentil 95 del total.',
    remedyLessonId: 'l2_4',
    remedyExperimentId: 'e10_corr',
  ),
  Confusion(
    id: 'sumar_desviaciones',
    name: 'Sumar desviaciones estándar',
    description: 'Calcular la desviación de una suma de variables independientes sumando sus desviaciones. Se suman las varianzas.',
    remedy: 'Con ρ = 0, la desviación del total es √2·20 y no 40: compruébalo en el laboratorio de correlación.',
    remedyLessonId: 'l2_4',
    remedyExperimentId: 'e10_corr',
  ),
  Confusion(
    id: 'normal_para_todo',
    name: 'Normal para todo',
    description: 'Modelar con una normal magnitudes positivas y asimétricas (costos, leyes, concentraciones): aparecen negativos y se subestima la cola.',
    remedy: 'Compara normal y lognormal con la misma media y desviación en el laboratorio de forma.',
    remedyLessonId: 'l2_2',
    remedyExperimentId: 'e11_shape',
  ),
  Confusion(
    id: 'media_es_tipico',
    name: 'La media es el valor típico',
    description: 'En salidas asimétricas, la media queda lejos de la mediana: la mayoría de los casos está por debajo (o encima) de ella.',
    remedy: 'Lee en la curva S qué fracción de resultados supera la media.',
    remedyLessonId: 'l3_1',
    remedyExperimentId: 'e14_scurve',
  ),
  Confusion(
    id: 'solo_la_media',
    name: 'Reportar solo la media',
    description: 'Resumir una simulación con un número. Lo que Monte Carlo aporta es la distribución: percentiles y probabilidades.',
    remedy: 'Revisa cómo leer la distribución de resultados: media, mediana, P10 y P90, probabilidad del umbral.',
    remedyLessonId: 'l3_1',
    remedyExperimentId: 'e15_compare',
  ),
  Confusion(
    id: 'media_bajo_limite_seguro',
    name: 'Media bajo el límite ⇒ sin riesgo',
    description: 'Concluir que no hay riesgo porque el promedio está del lado seguro del umbral. El riesgo está en la cola.',
    remedy: 'Calcula la probabilidad de superar el umbral, no solo la media.',
    remedyLessonId: 'l3_2',
    remedyExperimentId: 'e14_scurve',
  ),
  Confusion(
    id: 'cero_casos_cero_prob',
    name: 'Cero casos ⇒ probabilidad cero',
    description: 'Concluir que un evento es imposible porque no apareció en n iteraciones. Solo se puede decir que p es menor que ≈ 3/n.',
    remedy: 'Simula un evento con p = 0,002 usando 100 iteraciones y cuenta cuántas réplicas no lo ven.',
    remedyLessonId: 'l3_3',
    remedyExperimentId: 'e13_rare',
  ),
  Confusion(
    id: 'percentil_invertido',
    name: 'Leer el percentil al revés',
    description: 'Creer que P90 es un valor con 90 % de probabilidad de ser superado. Es el valor que no se supera en el 90 % de los casos.',
    remedy: 'Arrastra el umbral en la curva S hasta el P90 y lee la probabilidad acumulada.',
    remedyLessonId: 'l3_1',
    remedyExperimentId: 'e14_scurve',
  ),
  Confusion(
    id: 'se_vs_sd',
    name: 'Error estándar confundido con dispersión',
    description: 'Confundir la precisión de la estimación (s/√n, baja con más iteraciones) con la variabilidad del resultado (s, no baja).',
    remedy: 'Aumenta n y observa: el IC de la media se estrecha, el histograma no.',
    remedyLessonId: 'l1_4',
    remedyExperimentId: 'e12_sqrt_n',
  ),
  Confusion(
    id: 'sensibilidad_por_rango',
    name: 'La entrada con más rango es la que más influye',
    description: 'Juzgar la influencia por el ancho del rango de la entrada, sin mirar cómo entra en el modelo ni sus unidades.',
    remedy: 'Mira el gráfico de tornado del proyecto: el volumen tiene el mayor rango y no es la entrada que manda.',
    remedyLessonId: 'l3_4',
    remedyExperimentId: 'e16_tornado',
  ),
  Confusion(
    id: 'decision_por_media',
    name: 'Decidir solo por la media',
    description: 'Elegir la alternativa con mayor valor esperado sin mirar su riesgo ni la tolerancia de quien decide.',
    remedy: 'Compara dos alternativas por media, probabilidad de pérdida y percentil 5.',
    remedyLessonId: 'l3_2',
    remedyExperimentId: 'e15_compare',
  ),
  Confusion(
    id: 'estimadores_iguales',
    name: 'Solo importa n',
    description: 'Creer que todos los estimadores Monte Carlo tienen la misma precisión con el mismo n. Cambiar el estimador puede equivaler a multiplicar n.',
    remedy: 'Estima la misma área con acierto-fallo y con valor medio, con el mismo n.',
    remedyLessonId: 'l1_4',
    remedyExperimentId: 'e2_area',
  ),
  Confusion(
    id: 'eventos_raros_pocas_iter',
    name: 'Eventos raros con pocas iteraciones',
    description: 'Estimar una probabilidad pequeña con pocas iteraciones: el error relativo es enorme aunque el absoluto parezca pequeño.',
    remedy: 'Mira el error relativo de p̂ con n = 1 000 y con n = 10 000 cuando p = 0,002.',
    remedyLessonId: 'l3_3',
    remedyExperimentId: 'e13_rare',
  ),
  Confusion(
    id: 'sin_semilla',
    name: 'Resultados sin semilla',
    description: 'Reportar una simulación sin registrar la semilla, el generador y n: nadie puede reproducirla ni auditarla.',
    remedy: 'Repite una corrida con la misma semilla y compara: la reproducibilidad es parte del informe.',
    remedyLessonId: 'l1_2',
    remedyExperimentId: 'e4_lcg',
  ),
  Confusion(
    id: 'acertar_sin_entender',
    name: 'Acertar sin entender',
    description: 'Elegir la decisión correcta con una justificación equivocada. Acierta hoy, falla en el siguiente caso.',
    remedy: 'Relee la justificación correcta del ítem: es la parte que se transfiere a otros problemas.',
    remedyLessonId: 'l3_2',
  ),
];

Confusion? confusionById(String id) {
  for (final c in confusions) {
    if (c.id == id) return c;
  }
  return null;
}
