import '../models/content_models.dart';

/// Práctica: 12 ítems por módulo, en cuatro formatos. Cada distractor
/// declara la confusión que revela; cada respuesta numérica sale del
/// registro de cifras; los errores numéricos típicos se reconocen por su
/// valor.
const List<Exercise> exercises = [
  // =============================================================== M1
  Exercise(
    id: 'x1_01',
    moduleId: 'm1',
    type: ExerciseType.choice,
    prompt: 'Lanzas 2 000 dardos al cuadrado unitario y 1 580 caen dentro del cuarto de círculo. ¿Cuál es la estimación de π?',
    options: [
      Option('0,79', feedback: 'Esa es la fracción de aciertos, que estima π/4. Falta multiplicar por 4.'),
      Option('3,16', correct: true, feedback: 'Correcto: 4 · 1 580 / 2 000 = 3,16.'),
      Option('3,14159, porque el método converge a π', feedback: 'El método converge a π, pero con 2 000 dardos lo que tienes es una estimación con error, no π.', confusion: 'una_corrida_es_verdad'),
    ],
    explanation: 'La fracción de aciertos estima el área π/4; se multiplica por 4. El resultado es una estimación: otra semilla daría otro valor cercano.',
    targets: ['una_corrida_es_verdad'],
  ),
  Exercise(
    id: 'x1_02',
    moduleId: 'm1',
    type: ExerciseType.numeric,
    prompt: 'La desviación de un dardo (4 · indicadora) es {{pi_se_coef}}. ¿Cuál es el error estándar de la estimación de π con 1 000 dardos?',
    answerFigure: 'pi_se_1000',
    relTolerance: 0.03,
    wrongPatterns: [
      WrongPattern(figure: 'pi_se_coef', confusion: 'se_vs_sd', feedback: 'Esa es la desviación de un solo dardo. El error de la media se divide entre √n.'),
      WrongPattern(figure: 'pi_se_wrong_n', confusion: 'error_lineal_n', feedback: 'Dividiste entre n. El error estándar es s/√n, no s/n.'),
    ],
    explanation: 'EE = s/√n = {{pi_se_coef}}/√1 000 = {{pi_se_1000}}.',
    targets: ['se_vs_sd', 'error_lineal_n'],
  ),
  Exercise(
    id: 'x1_03',
    moduleId: 'm1',
    type: ExerciseType.choice,
    prompt: 'Simulas el VAN de un proyecto con 1 000 iteraciones y luego con 100 000. ¿Qué pasa con la desviación estándar de la distribución del VAN?',
    options: [
      Option('Se reduce unas 10 veces', feedback: 'Eso le pasa al error estándar de la media (s/√n), no a la dispersión del VAN.', confusion: 'se_vs_sd'),
      Option('Se mantiene aproximadamente igual; solo se estima con más precisión', correct: true, feedback: 'Correcto: la desviación describe el riesgo del proyecto, que no depende de cuánto simules.'),
      Option('Se reduce 100 veces', feedback: 'Ni la desviación ni el error estándar bajan en proporción a n.', confusion: 'error_lineal_n'),
    ],
    explanation: 'La desviación de la salida es una propiedad del sistema (su riesgo). Con más iteraciones se estima mejor, pero no se achica. Lo que se achica es el error estándar de la media.',
    targets: ['se_vs_sd'],
  ),
  Exercise(
    id: 'x1_04',
    moduleId: 'm1',
    type: ExerciseType.decision,
    prompt: 'Tu simulación de π con 500 dardos dio 3,19. ¿Cómo lo reportas en el informe?',
    options: [
      Option('«π ≈ 3,19»', feedback: 'Un número sin su error no permite juzgar si 3,19 es compatible con π.', confusion: 'una_corrida_es_verdad'),
      Option('«3,19 ± {{pi_half_500}} (IC 95 %, n = 500, xoshiro128**, semilla registrada)»', correct: true, feedback: 'Correcto: estimación, error, tamaño y forma de reproducirla.'),
      Option('Repites con otras semillas hasta obtener 3,14 y reportas esa', feedback: 'Elegir la corrida que te conviene es sesgar el resultado.', confusion: 'una_corrida_es_verdad'),
    ],
    justifications: [
      Option('Toda estimación Monte Carlo tiene error de muestreo; el intervalo lo cuantifica y la semilla permite reproducirla', correct: true, feedback: 'Esa es la razón que se transfiere a cualquier simulación.'),
      Option('Porque 3,19 está lejos de π y hay que justificar la diferencia', feedback: 'El intervalo se reporta siempre, esté cerca o lejos del valor esperado.', confusion: 'acertar_sin_entender'),
      Option('Porque el formato de informe lo exige', feedback: 'El formato lo exige por una razón: sin error ni semilla el resultado no se puede evaluar.', confusion: 'acertar_sin_entender'),
    ],
    explanation: 'Con n = 500, el IC 95 % tiene semiamplitud ±{{pi_half_500}}: 3,19 es perfectamente compatible con π. Reportar la semilla y el generador permite reproducir exactamente la corrida.',
    targets: ['una_corrida_es_verdad', 'sin_semilla'],
  ),
  Exercise(
    id: 'x1_05',
    moduleId: 'm1',
    type: ExerciseType.choice,
    prompt: 'Un generador produce un histograma perfectamente plano en 20 clases. ¿Qué falta verificar antes de usarlo en una simulación?',
    options: [
      Option('Nada: la uniformidad es la propiedad que importa', feedback: 'Un congruencial pobre tiene histograma plano y pares consecutivos alineados en rectas.', confusion: 'histograma_prueba_calidad'),
      Option('Que los valores consecutivos sean independientes y que el periodo sea enorme', correct: true, feedback: 'Correcto: uniforme, independiente y con periodo mucho mayor que las iteraciones.'),
      Option('Que no use semilla, para que sea azar verdadero', feedback: 'Todo generador de software usa una semilla; es lo que lo hace reproducible.', confusion: 'pseudo_es_azar_real'),
    ],
    explanation: 'La calidad de un generador se juzga por uniformidad, independencia (pares, ternas) y periodo. El histograma solo prueba lo primero.',
    targets: ['histograma_prueba_calidad'],
  ),
  Exercise(
    id: 'x1_06',
    moduleId: 'm1',
    type: ExerciseType.choice,
    prompt: 'Un colega dice que fijar la semilla «hace trampa» porque los números ya no son aleatorios. ¿Qué le respondes?',
    options: [
      Option('Tiene razón: con semilla fija la simulación deja de ser válida', feedback: 'Los números siguen teniendo las propiedades estadísticas del azar; solo se vuelven repetibles.', confusion: 'pseudo_es_azar_real'),
      Option('La semilla hace la corrida reproducible; cambiarla da otra muestra igualmente válida', correct: true, feedback: 'Correcto: reproducibilidad para auditar, varias semillas para ver el error.'),
      Option('Da igual: la semilla no hace falta registrarla', feedback: 'Sin semilla nadie puede reproducir ni auditar tu resultado.', confusion: 'sin_semilla'),
    ],
    explanation: 'Los generadores de software son deterministas por diseño. Fijar la semilla no sesga nada: solo permite repetir exactamente la misma muestra.',
    targets: ['pseudo_es_azar_real', 'sin_semilla'],
  ),
  Exercise(
    id: 'x1_07',
    moduleId: 'm1',
    type: ExerciseType.numeric,
    prompt: 'Simulas tiempos entre fallas exponenciales con media 2 h usando x = −2·ln(1 − u). ¿Qué tiempo produce u = 0,5? (en horas)',
    answerFigure: 'exp_median',
    relTolerance: 0.02,
    unit: 'h',
    wrongPatterns: [
      WrongPattern(figure: 'exp_mean', confusion: 'media_es_tipico', feedback: 'u = 0,5 da la mediana, no la media. En la exponencial la mediana es menor que la media.'),
      WrongPattern(figure: 'exp_wrong_scale', confusion: 'uniforme_directa', feedback: 'Multiplicaste u por la media. Hay que aplicar la inversa de la acumulada: −2·ln(1 − u).'),
    ],
    explanation: 'x = −2·ln(0,5) = 2·ln 2 = {{exp_median}} h: la mediana.',
    targets: ['uniforme_directa', 'media_es_tipico'],
  ),
  Exercise(
    id: 'x1_08',
    moduleId: 'm1',
    type: ExerciseType.choice,
    prompt: 'En la transformada inversa, el número u se proyecta horizontalmente sobre una curva y se baja al eje x. ¿Qué curva?',
    options: [
      Option('La densidad f(x)', feedback: 'La densidad no va de 0 a 1 ni es monótona: no se puede invertir para obtener x.', confusion: 'inversa_con_densidad'),
      Option('La acumulada F(x)', correct: true, feedback: 'Correcto: F va de 0 a 1 y es creciente, así que cada u tiene un único x.'),
      Option('Una recta de pendiente igual a la media', feedback: 'Eso produciría una uniforme escalada, no la distribución buscada.', confusion: 'uniforme_directa'),
    ],
    explanation: 'X = F⁻¹(U): la acumulada convierte probabilidades en valores.',
    targets: ['inversa_con_densidad'],
  ),
  Exercise(
    id: 'x1_09',
    moduleId: 'm1',
    type: ExerciseType.choice,
    prompt: 'Una variable vale A, B o C con probabilidades 0,2; 0,5 y 0,3, y se asignan tramos de [0, 1) en ese orden. ¿Qué valor produce u = 0,65?',
    options: [
      Option('A', feedback: 'El tramo de A es [0; 0,2).'),
      Option('B', correct: true, feedback: 'Correcto: B ocupa [0,2; 0,7) y 0,65 está dentro.'),
      Option('C', feedback: 'C empieza en 0,7.'),
    ],
    explanation: 'Tramos acumulados: A [0; 0,2), B [0,2; 0,7), C [0,7; 1). Cada tramo mide su probabilidad.',
    targets: ['uniforme_directa'],
  ),
  Exercise(
    id: 'x1_10',
    moduleId: 'm1',
    type: ExerciseType.numeric,
    prompt: 'Para el área bajo e^(−x²), el estimador acierto-fallo tiene desviación {{area_sd_hit}} por iteración y el de valor medio {{area_sd_mean}}. ¿Cuántas veces más iteraciones necesita acierto-fallo para lograr el mismo error estándar?',
    answerFigure: 'area_var_ratio',
    relTolerance: 0.04,
    unit: 'veces',
    wrongPatterns: [
      WrongPattern(figure: 'area_sd_ratio', confusion: 'error_lineal_n', feedback: 'Ese es el cociente de desviaciones. Como el error va con 1/√n, las iteraciones escalan con el cuadrado.'),
    ],
    explanation: '(s₁/s₂)² = ({{area_sd_hit}}/{{area_sd_mean}})² ≈ {{area_var_ratio}}.',
    targets: ['estimadores_iguales', 'error_lineal_n'],
  ),
  Exercise(
    id: 'x1_11',
    moduleId: 'm1',
    type: ExerciseType.ordering,
    prompt: 'Ordena los pasos para estimar π por Monte Carlo y reportarlo.',
    steps: [
      'Elegir el generador y registrar la semilla',
      'Generar un punto (U, V) uniforme en el cuadrado',
      'Registrar si U² + V² ≤ 1',
      'Repetir n veces',
      'Calcular 4 · aciertos / n y su error estándar',
      'Reportar la estimación con su IC 95 %, n y semilla',
    ],
    explanation: 'La semilla va primero porque define toda la secuencia; el error se calcula al final y se reporta junto con la estimación.',
    targets: ['sin_semilla'],
  ),
  Exercise(
    id: 'x1_12',
    moduleId: 'm1',
    type: ExerciseType.choice,
    prompt: 'Dos métodos estiman la misma área con n = 10 000. El A tiene desviación 0,4 por iteración y el B 0,2. ¿Qué concluyes?',
    options: [
      Option('Tienen la misma precisión: usan el mismo n', feedback: 'La precisión depende de n y de la desviación por iteración.', confusion: 'estimadores_iguales'),
      Option('B tiene la mitad de error; A necesitaría 4 veces más iteraciones para igualarlo', correct: true, feedback: 'Correcto: error ∝ s/√n.'),
      Option('B tiene la cuarta parte del error', feedback: 'El error es proporcional a s: la mitad de s da la mitad de error.', confusion: 'error_lineal_n'),
    ],
    explanation: 'EE = s/√n: con la mitad de s, el error es la mitad. Para igualarlo, A necesita (0,4/0,2)² = 4 veces más iteraciones.',
    targets: ['estimadores_iguales'],
  ),

  // =============================================================== M2
  Exercise(
    id: 'x2_01',
    moduleId: 'm2',
    type: ExerciseType.choice,
    prompt: 'Un jefe de obra estima que una tarea dura como mínimo 5 días, lo más probable 8 y como máximo 14. ¿Qué distribución usas?',
    options: [
      Option('Triangular(5; 8; 14)', correct: true, feedback: 'Correcto: usa exactamente la información disponible, incluida la asimetría.'),
      Option('Normal con media 8', feedback: 'La normal es simétrica y no respeta el mínimo: ignora que la tarea puede atrasarse más de lo que puede adelantarse.', confusion: 'normal_para_todo'),
      Option('Uniforme(5; 14)', feedback: 'Descarta la información de que 8 es lo más probable.'),
    ],
    explanation: 'Con mínimo, más probable y máximo, la triangular (o la PERT) es la elección natural. Además es asimétrica: su media es 9, no 8.',
    targets: ['normal_para_todo'],
  ),
  Exercise(
    id: 'x2_02',
    moduleId: 'm2',
    type: ExerciseType.choice,
    prompt: 'Una planta tiene capacidad 100 y la demanda diaria media es 100 (incierta). ¿Cuánto vende en promedio?',
    options: [
      Option('Menos de 100', correct: true, feedback: 'Correcto: los días de demanda alta pierde ventas y los de demanda baja no las recupera.'),
      Option('Exactamente 100', feedback: 'Eso es evaluar el modelo en el promedio. Con min(D, C), el promedio de la salida es menor.', confusion: 'promedio_de_entradas'),
      Option('Más de 100', feedback: 'Nunca puede vender más que su capacidad.'),
    ],
    explanation: 'E[min(D, C)] ≤ min(E[D], C). Con demanda Normal(100; 25), vende en promedio {{cap_expected_sales}}.',
    targets: ['promedio_de_entradas'],
  ),
  Exercise(
    id: 'x2_03',
    moduleId: 'm2',
    type: ExerciseType.numeric,
    prompt: 'Demanda Normal(100; 25) y capacidad 100. Usa el laboratorio de capacidad o el simulador: ¿cuáles son las ventas esperadas por día?',
    answerFigure: 'cap_expected_sales',
    relTolerance: 0.015,
    unit: 'unidades',
    wrongPatterns: [
      WrongPattern(figure: 'cap_plan_sales', confusion: 'promedio_de_entradas', feedback: 'Ese es el plan con demanda media. Simula: los excesos se pierden.'),
    ],
    explanation: 'E[min(D; 100)] = 100 − 25·φ(0) = {{cap_expected_sales}}.',
    targets: ['promedio_de_entradas'],
  ),
  Exercise(
    id: 'x2_04',
    moduleId: 'm2',
    type: ExerciseType.numeric,
    prompt: 'Dos tareas en paralelo, cada una Triangular(5; 8; 14) días, y luego 5 días más. ¿Probabilidad (en %) de terminar en 14 días o menos?',
    answerFigure: 'merge_p_two',
    answerIsPercent: true,
    relTolerance: 0.03,
    unit: '%',
    wrongPatterns: [
      WrongPattern(figure: 'merge_p_one', confusion: 'paralelo_sin_sesgo', feedback: 'Esa es la probabilidad con una sola ruta. Con dos, hay que esperar a la más lenta: F(9)².'),
    ],
    explanation: 'P(max(A, B) ≤ 9) = F(9)² = {{merge_p_one}}² = {{merge_p_two}}.',
    targets: ['paralelo_sin_sesgo'],
  ),
  Exercise(
    id: 'x2_05',
    moduleId: 'm2',
    type: ExerciseType.numeric,
    prompt: 'Dos costos independientes tienen desviación 20 cada uno. ¿Cuál es la desviación del costo total?',
    answerFigure: 'corr_sd_0',
    relTolerance: 0.02,
    wrongPatterns: [
      WrongPattern(figure: 'corr_sd_wrong', confusion: 'sumar_desviaciones', feedback: 'Sumaste desviaciones. Para independientes se suman varianzas: √(20² + 20²).'),
    ],
    explanation: '√(20² + 20²) = {{corr_sd_0}}.',
    targets: ['sumar_desviaciones'],
  ),
  Exercise(
    id: 'x2_06',
    moduleId: 'm2',
    type: ExerciseType.choice,
    prompt: 'Mano de obra y materiales suben juntos con la inflación, pero se simulan como independientes. ¿Qué pasa con el riesgo estimado del costo total?',
    options: [
      Option('Se subestima la cola alta', correct: true, feedback: 'Correcto: con correlación positiva los extremos coinciden y la cola del total crece.'),
      Option('Se sobrestima la cola alta', feedback: 'Es al revés: la independencia hace que los extremos se compensen más de lo real.'),
      Option('No cambia: cada costo tiene su distribución correcta', feedback: 'Las distribuciones individuales no bastan; la dependencia cambia la del total.', confusion: 'ignorar_correlacion'),
    ],
    explanation: 'Var(X₁ + X₂) = σ₁² + σ₂² + 2ρσ₁σ₂. Con ρ = 0,8 el P95 sube de {{corr_p95_0}} a {{corr_p95_08}}.',
    targets: ['ignorar_correlacion'],
  ),
  Exercise(
    id: 'x2_07',
    moduleId: 'm2',
    type: ExerciseType.decision,
    prompt: 'Los costos de reparación de una flota son siempre positivos y a veces muy altos; los datos dan media 100 y desviación 50. ¿Qué distribución usas?',
    options: [
      Option('Lognormal con media 100 y desviación 50', correct: true, feedback: 'Correcto.'),
      Option('Normal(100; 50)', feedback: 'Genera costos negativos y una cola derecha demasiado delgada.', confusion: 'normal_para_todo'),
      Option('Uniforme(0; 200)', feedback: 'Pone un techo artificial en 200, justo donde está el riesgo.'),
    ],
    justifications: [
      Option('Es positiva y asimétrica: la normal daría {{shape_normal_neg}} de costos negativos y subestimaría P(X > 200)', correct: true, feedback: 'Esa es la razón: forma y soporte.'),
      Option('La lognormal siempre tiene mayor media que la normal', feedback: 'Aquí ambas tienen la misma media. La diferencia está en la forma.', confusion: 'acertar_sin_entender'),
      Option('La lognormal es la distribución por defecto en simulación', feedback: 'No hay distribución por defecto: se elige por lo que se sabe de la variable.', confusion: 'acertar_sin_entender'),
    ],
    explanation: 'Con la misma media y desviación, P(X > 200) es {{shape_lognormal_tail}} con lognormal y {{shape_normal_tail}} con normal.',
    targets: ['normal_para_todo'],
  ),
  Exercise(
    id: 'x2_08',
    moduleId: 'm2',
    type: ExerciseType.choice,
    prompt: 'Con precio, costo y volumen en sus valores más probables, el VAN es {{npv_mode}}. ¿Es ese el VAN esperado del proyecto?',
    options: [
      Option('No: con triangulares asimétricas, el VAN esperado es {{npv_mean}}', correct: true, feedback: 'Correcto: las modas no son las medias.'),
      Option('Sí: el escenario más probable es el esperado', feedback: 'Solo coinciden con distribuciones simétricas.', confusion: 'mas_probable_es_esperado'),
      Option('Sí, si la simulación usa suficientes iteraciones', feedback: 'Las iteraciones no cambian a qué converge el modelo.', confusion: 'mas_n_corrige_modelo'),
    ],
    explanation: 'El precio va de 8 a 11 con moda 10: su media es {{npv_price_mean}}. El volumen va de 30 a 55 con moda 50: su media es {{npv_volume_mean}}. El VAN medio cae a {{npv_mean}}.',
    targets: ['mas_probable_es_esperado'],
  ),
  Exercise(
    id: 'x2_09',
    moduleId: 'm2',
    type: ExerciseType.numeric,
    prompt: 'Simula el proyecto de VAN (plantilla del simulador o laboratorio). ¿Cuál es la probabilidad de perder dinero, en %?',
    answerFigure: 'npv_ploss',
    answerIsPercent: true,
    relTolerance: 0.05,
    unit: '%',
    wrongPatterns: [
      WrongPattern(figure: 'zero', confusion: 'mas_probable_es_esperado', feedback: 'El escenario más probable da VAN positivo, pero la distribución tiene mucha probabilidad bajo cero.'),
    ],
    explanation: 'P(VAN < 0) = {{npv_ploss}}: más de un tercio, aunque el escenario más probable gane {{npv_mode}}.',
    targets: ['mas_probable_es_esperado', 'solo_la_media'],
  ),
  Exercise(
    id: 'x2_10',
    moduleId: 'm2',
    type: ExerciseType.ordering,
    prompt: 'Ordena los pasos para construir un estudio de simulación.',
    steps: [
      'Formular la pregunta de decisión y el umbral',
      'Construir y verificar el modelo determinista',
      'Asignar distribuciones a las entradas inciertas',
      'Definir la dependencia entre entradas',
      'Simular n iteraciones con semilla registrada',
      'Analizar percentiles, probabilidades y sensibilidad',
    ],
    explanation: 'Sin pregunta no sabes qué salida mirar; sin modelo verificado, la simulación reproduce errores con mucha precisión.',
    targets: ['mas_n_corrige_modelo'],
  ),
  Exercise(
    id: 'x2_11',
    moduleId: 'm2',
    type: ExerciseType.choice,
    prompt: 'Con entradas independientes, ¿en cuál de estos modelos el escenario promedio sí da la salida promedio?',
    options: [
      Option('Costo total = X₁ + X₂ + X₃', correct: true, feedback: 'Correcto: la suma es lineal.'),
      Option('Ventas = min(Demanda, Capacidad)', feedback: 'El mínimo no es lineal: el promedio de la salida es menor.', confusion: 'promedio_de_entradas'),
      Option('Plazo = max(A, B) + C', feedback: 'El máximo no es lineal: el promedio del plazo es mayor.', confusion: 'paralelo_sin_sesgo'),
    ],
    explanation: 'E[g(X)] = g(E[X]) solo si g es lineal. Mínimos, máximos, umbrales y productos de variables correlacionadas rompen la igualdad.',
    targets: ['promedio_de_entradas'],
  ),
  Exercise(
    id: 'x2_12',
    moduleId: 'm2',
    type: ExerciseType.numeric,
    prompt: 'Dos costos Normal(100; 20) con correlación 0,8. ¿Cuál es el percentil 95 del total?',
    answerFigure: 'corr_p95_08',
    relTolerance: 0.01,
    wrongPatterns: [
      WrongPattern(figure: 'corr_p95_0', confusion: 'ignorar_correlacion', feedback: 'Ese es el P95 con independencia. Con ρ = 0,8 la desviación del total crece.'),
    ],
    explanation: 'σ = 20·√(2 + 2·0,8) = {{corr_sd_08}}; P95 = 200 + 1,645·σ = {{corr_p95_08}}.',
    targets: ['ignorar_correlacion'],
  ),

  // =============================================================== M3
  Exercise(
    id: 'x3_01',
    moduleId: 'm3',
    type: ExerciseType.choice,
    prompt: 'El P90 del costo simulado de una obra es 1,8 millones. ¿Qué significa?',
    options: [
      Option('Hay 90 % de probabilidad de que el costo supere 1,8 millones', feedback: 'Es al revés: el 90 % de los resultados queda por debajo.', confusion: 'percentil_invertido'),
      Option('Hay 90 % de probabilidad de que el costo sea 1,8 millones o menos', correct: true, feedback: 'Correcto.'),
      Option('El costo medio es 1,8 millones', feedback: 'La media y el P90 son cosas distintas.', confusion: 'solo_la_media'),
    ],
    explanation: 'P(Costo ≤ P90) = 0,90. Presupuestar al P90 deja 10 % de probabilidad de sobrecosto.',
    targets: ['percentil_invertido'],
  ),
  Exercise(
    id: 'x3_02',
    moduleId: 'm3',
    type: ExerciseType.numeric,
    prompt: 'El costo es lognormal con mediana {{sc_median}} y σ_ln = 0,6. Si presupuestas exactamente la media ({{sc_mean}}), ¿cuál es la probabilidad de sobrecosto, en %?',
    answerFigure: 'sc_p_over_mean',
    answerIsPercent: true,
    relTolerance: 0.03,
    unit: '%',
    wrongPatterns: [
      WrongPattern(figure: 'half', confusion: 'media_es_tipico', feedback: 'Eso sería cierto para la mediana. En una distribución con cola derecha, la media está por encima.'),
    ],
    explanation: 'P(X > media) = 1 − Φ(σ/2) = 1 − Φ(0,3) = {{sc_p_over_mean}}.',
    targets: ['media_es_tipico'],
  ),
  Exercise(
    id: 'x3_03',
    moduleId: 'm3',
    type: ExerciseType.numeric,
    prompt: 'Una corrida piloto da desviación 140 para el VAN. ¿Cuántas iteraciones necesitas para que el IC 95 % de la media tenga semiamplitud 5?',
    answerFigure: 'n_req_ex',
    relTolerance: 0.02,
    unit: 'iteraciones',
    wrongPatterns: [
      WrongPattern(figure: 'n_req_ex_wrong', confusion: 'error_lineal_n', feedback: 'Olvidaste elevar al cuadrado: n = (1,96·s/E)².'),
    ],
    explanation: 'n = (1,96 · 140 / 5)² ≈ {{n_req_ex}}.',
    targets: ['error_lineal_n'],
  ),
  Exercise(
    id: 'x3_04',
    moduleId: 'm3',
    type: ExerciseType.choice,
    prompt: 'En 1 000 iteraciones del modelo de una presa no ocurrió ningún desborde. ¿Qué concluyes?',
    options: [
      Option('La probabilidad de desborde es 0', feedback: 'Cero casos en n solo acota la probabilidad.', confusion: 'cero_casos_cero_prob'),
      Option('La probabilidad es menor que ~{{rare_rule3_1000}} (regla del tres); hacen falta más iteraciones para estimarla', correct: true, feedback: 'Correcto.'),
      Option('La probabilidad es 1/1 000', feedback: 'Eso supondría que hubo un caso.'),
    ],
    explanation: 'Con 0 casos en n, la cota superior al 95 % es ≈ 3/n. Un evento con p = 0,002 no aparece en 1 000 iteraciones el {{rare_p0_1000}} de las veces.',
    targets: ['cero_casos_cero_prob'],
  ),
  Exercise(
    id: 'x3_05',
    moduleId: 'm3',
    type: ExerciseType.numeric,
    prompt: '0 fallas en 1 000 iteraciones. ¿Cuál es la cota superior aproximada al 95 % de la probabilidad de falla, en %?',
    answerFigure: 'rare_rule3_1000',
    answerIsPercent: true,
    relTolerance: 0.05,
    unit: '%',
    wrongPatterns: [
      WrongPattern(figure: 'zero', confusion: 'cero_casos_cero_prob', feedback: '0 es la estimación puntual, no la cota. Con 0 casos se reporta p < 3/n.'),
    ],
    explanation: '3/1 000 = {{rare_rule3_1000}}.',
    targets: ['cero_casos_cero_prob'],
  ),
  Exercise(
    id: 'x3_06',
    moduleId: 'm3',
    type: ExerciseType.decision,
    prompt: 'Una pequeña empresa quiebra si pierde dinero este año. Opción A: utilidad Normal(120; 80). Opción B: Normal(100; 15). ¿Cuál elige?',
    options: [
      Option('A', feedback: 'A tiene mayor media, pero pierde dinero el {{cmp_a_ploss}} de las veces: para esta empresa, eso es quebrar.', confusion: 'decision_por_media'),
      Option('B', correct: true, feedback: 'Correcto para este decisor.'),
    ],
    justifications: [
      Option('La probabilidad de pérdida de A ({{cmp_a_ploss}}) es inaceptable para quien quiebra si pierde; B prácticamente nunca pierde', correct: true, feedback: 'El criterio está explícito: tolerancia al riesgo.'),
      Option('B tiene mayor utilidad media', feedback: 'Falso: A tiene mayor media. Elegiste bien por una razón equivocada.', confusion: 'acertar_sin_entender'),
      Option('Menor desviación siempre es mejor', feedback: 'No siempre: un inversor diversificado podría preferir A. Depende del decisor.', confusion: 'acertar_sin_entender'),
    ],
    explanation: 'La simulación muestra el intercambio: A gana 20 más en promedio con P5 = {{cmp_a_p5}}; B tiene P5 = {{cmp_b_p5}}. El criterio lo pone quien decide.',
    targets: ['decision_por_media', 'solo_la_media'],
  ),
  Exercise(
    id: 'x3_07',
    moduleId: 'm3',
    type: ExerciseType.choice,
    prompt: 'En el proyecto, el volumen va de 30 a 55 (rango 25) y el precio de 8 a 11 (rango 3). ¿Cuál influye más en el VAN?',
    options: [
      Option('El volumen, por su rango mayor', feedback: 'El rango en unidades no se compara entre entradas distintas.', confusion: 'sensibilidad_por_rango'),
      Option('El precio: explica cerca de {{tornado_share_price}} de la varianza del VAN', correct: true, feedback: 'Correcto: cada sol de precio se multiplica por el volumen.'),
      Option('Todas por igual', feedback: 'El tornado muestra diferencias claras.'),
    ],
    explanation: 'La influencia depende de la incertidumbre de la entrada y de cómo entra en el modelo. Precio {{tornado_share_price}}, volumen {{tornado_share_volume}}, costo {{tornado_share_cost}}.',
    targets: ['sensibilidad_por_rango'],
  ),
  Exercise(
    id: 'x3_08',
    moduleId: 'm3',
    type: ExerciseType.choice,
    prompt: 'Un modelo con 100 000 iteraciones da un IC 95 % muy estrecho para el VAN. ¿Qué garantiza?',
    options: [
      Option('Que el VAN real está en ese intervalo', feedback: 'Solo si el modelo representa bien la realidad.', confusion: 'mas_n_corrige_modelo'),
      Option('Que la media del modelo está bien estimada; la validez del modelo es otra cuestión', correct: true, feedback: 'Correcto: precisión no es validez.'),
      Option('Que el proyecto es de bajo riesgo', feedback: 'El IC mide precisión de la media, no el riesgo del proyecto.', confusion: 'se_vs_sd'),
    ],
    explanation: 'El IC mide el error de muestreo. Si las distribuciones o la fórmula están mal, la simulación converge con mucha precisión a una respuesta equivocada.',
    targets: ['mas_n_corrige_modelo', 'se_vs_sd'],
  ),
  Exercise(
    id: 'x3_09',
    moduleId: 'm3',
    type: ExerciseType.numeric,
    prompt: 'La salida tiene desviación 200 y simulaste 10 000 iteraciones. ¿Cuál es el error estándar de la media?',
    answerFigure: 'se_ex',
    relTolerance: 0.02,
    wrongPatterns: [
      WrongPattern(figure: 'se_ex_wrong_n', confusion: 'error_lineal_n', feedback: 'Dividiste entre n; es entre √n.'),
      WrongPattern(figure: 'se_ex_sd', confusion: 'se_vs_sd', feedback: 'Esa es la desviación de la salida, no el error de su media.'),
    ],
    explanation: '200/√10 000 = {{se_ex}}.',
    targets: ['error_lineal_n', 'se_vs_sd'],
  ),
  Exercise(
    id: 'x3_10',
    moduleId: 'm3',
    type: ExerciseType.choice,
    prompt: 'Un informe ambiental dice: «la concentración media simulada es {{amb_mean}}, bajo el límite de 50; no hay riesgo». ¿Qué falta?',
    options: [
      Option('Nada: la media está bajo el límite', feedback: 'El riesgo está en la cola, no en la media.', confusion: 'media_bajo_limite_seguro'),
      Option('La probabilidad de superar 50 y cuántos días al año implica', correct: true, feedback: 'Correcto: con esa distribución, se supera el límite unos {{amb_days}} días al año.'),
      Option('Más iteraciones para confirmar la media', feedback: 'La media ya está bien estimada; la pregunta es otra.', confusion: 'mas_n_corrige_modelo'),
    ],
    explanation: 'P(C > 50) = {{amb_p_exceed}}: con la media bajo el límite, el límite se supera {{amb_days}} días al año.',
    targets: ['media_bajo_limite_seguro'],
  ),
  Exercise(
    id: 'x3_11',
    moduleId: 'm3',
    type: ExerciseType.ordering,
    prompt: 'Ordena las secciones de un informe de resultados de simulación.',
    steps: [
      'Pregunta de decisión y umbral de riesgo',
      'Modelo y supuestos: distribuciones, dependencia, horizonte',
      'Configuración: n, generador y semilla',
      'Media con su IC 95 % y precisión alcanzada',
      'Percentiles P10–P50–P90 y probabilidad del umbral',
      'Sensibilidad y recomendación con criterio de riesgo explícito',
    ],
    explanation: 'Quien lee primero debe saber qué se pregunta y bajo qué supuestos; luego, cuán preciso es el resultado; al final, qué hacer.',
    targets: ['solo_la_media'],
  ),
  Exercise(
    id: 'x3_12',
    moduleId: 'm3',
    type: ExerciseType.numeric,
    prompt: 'Un evento tiene p = 0,002 y simulas 10 000 iteraciones. ¿Cuál es el error estándar relativo de p̂ (error estándar / p), en %?',
    answerFigure: 'rare_relse_10000',
    answerIsPercent: true,
    relTolerance: 0.04,
    unit: '%',
    wrongPatterns: [
      WrongPattern(figure: 'rare_abs_se_10000', confusion: 'eventos_raros_pocas_iter', feedback: 'Ese es el error absoluto: parece pequeño, pero relativo a p es enorme.'),
    ],
    explanation: '√((1 − p)/(n·p)) = {{rare_relse_10000}}: aun con 10 000 iteraciones, p̂ puede equivocarse en más de un 20 %.',
    targets: ['eventos_raros_pocas_iter'],
  ),
];

List<Exercise> exercisesOf(String moduleId) =>
    [for (final e in exercises) if (e.moduleId == moduleId) e];

Exercise? exerciseById(String id) {
  for (final e in exercises) {
    if (e.id == id) return e;
  }
  return null;
}
