import '../models/content_models.dart';

const List<GlossaryTerm> glossary = [
  GlossaryTerm('Método Monte Carlo', 'Estimar una cantidad expresándola como el promedio de un experimento aleatorio y repitiendo ese experimento muchas veces en computadora.', example: 'π ≈ 4 · (puntos dentro del cuarto de círculo) / (puntos totales).'),
  GlossaryTerm('Iteración', 'Una repetición del modelo: se muestrean todas las entradas y se calcula la salida una vez.'),
  GlossaryTerm('Número pseudoaleatorio', 'Número producido por una regla determinista que imita las propiedades estadísticas del azar.'),
  GlossaryTerm('Semilla', 'Estado inicial del generador. La misma semilla produce la misma secuencia y hace reproducible la simulación.'),
  GlossaryTerm('Generador congruencial lineal (LCG)', 'Generador xₖ₊₁ = (a·xₖ + c) mod m. Con parámetros pobres, sus pares consecutivos caen sobre pocas rectas.'),
  GlossaryTerm('Periodo', 'Cantidad de números que produce un generador antes de repetir la secuencia.'),
  GlossaryTerm('xoshiro128**', 'Generador moderno de periodo 2¹²⁸ − 1 que usa esta app.'),
  GlossaryTerm('Distribución uniforme', 'Todos los valores de un intervalo son igualmente probables. U(0, 1) es la materia prima de toda simulación.'),
  GlossaryTerm('Función de distribución acumulada (F)', 'F(x) = P(X ≤ x). Crece de 0 a 1 y es la curva que se invierte para simular.'),
  GlossaryTerm('Densidad (f)', 'Probabilidad por unidad de x en una variable continua. El área bajo f entre a y b es P(a < X < b).'),
  GlossaryTerm('Transformada inversa', 'Método para simular cualquier distribución: X = F⁻¹(U), con U uniforme.'),
  GlossaryTerm('Distribución triangular', 'Definida por mínimo, más probable y máximo. Usual cuando la información viene de expertos.'),
  GlossaryTerm('Distribución normal', 'Simétrica, en forma de campana. Adecuada para sumas de muchos efectos pequeños; admite valores negativos.'),
  GlossaryTerm('Distribución lognormal', 'Su logaritmo es normal. Positiva y con cola derecha: costos, leyes de mineral, concentraciones.'),
  GlossaryTerm('Distribución exponencial', 'Tiempo hasta un evento que ocurre al azar a ritmo constante. Sin memoria.'),
  GlossaryTerm('Bernoulli', 'Variable que vale 1 con probabilidad p y 0 con probabilidad 1 − p.'),
  GlossaryTerm('Ley de los grandes números', 'El promedio de muchas repeticiones independientes se acerca al valor esperado.'),
  GlossaryTerm('Error estándar', 'Desviación de una estimación: s/√n. Mide la precisión de la media simulada, no el riesgo del sistema.'),
  GlossaryTerm('Intervalo de confianza (IC 95 %)', 'Rango estimación ± 1,96·error estándar. Así se reporta una estimación Monte Carlo.'),
  GlossaryTerm('Ley de √n', 'Para reducir el error a la mitad hacen falta cuatro veces más iteraciones.'),
  GlossaryTerm('Acierto-fallo', 'Estimador que cuenta la fracción de puntos que cumplen una condición. Simple, pero de varianza alta.'),
  GlossaryTerm('Estimador de valor medio', 'Estima una integral promediando f(U). Suele tener menor varianza que acierto-fallo.'),
  GlossaryTerm('Reducción de varianza', 'Técnicas que obtienen la misma precisión con menos iteraciones cambiando el estimador.'),
  GlossaryTerm('Modelo de simulación', 'Entradas inciertas + fórmula o lógica + salida que responde una pregunta de decisión.'),
  GlossaryTerm('Variable de entrada', 'Cantidad incierta del modelo descrita por una distribución.'),
  GlossaryTerm('Variable de salida', 'Resultado calculado en cada iteración cuya distribución se analiza.'),
  GlossaryTerm('Falacia de los promedios', 'Error de suponer que las entradas en su promedio producen la salida promedio. Falla con mínimos, máximos y umbrales.'),
  GlossaryTerm('Sesgo de fusión', 'Retraso sistemático cuando varias rutas paralelas convergen: el proyecto espera a la más lenta.'),
  GlossaryTerm('Correlación (ρ)', 'Medida de cuánto se mueven juntas dos variables, entre −1 y 1.'),
  GlossaryTerm('Cópula gaussiana', 'Forma de imponer correlación entre entradas conservando la distribución de cada una.'),
  GlossaryTerm('VAN', 'Valor actual neto: suma de flujos descontados menos la inversión. VAN < 0 significa destruir valor.'),
  GlossaryTerm('Factor de anualidad', 'Σ 1/(1 + r)ᵗ para t = 1..n. Convierte un flujo anual constante en su valor actual.'),
  GlossaryTerm('Histograma', 'Gráfico de frecuencias por clases: muestra la forma de la distribución simulada.'),
  GlossaryTerm('Curva S', 'Gráfico de la acumulada empírica: para cada valor, la probabilidad de no superarlo.'),
  GlossaryTerm('Percentil (P10, P50, P90)', 'Valor que no se supera en ese porcentaje de las iteraciones. P50 es la mediana.'),
  GlossaryTerm('Mediana', 'Valor que deja la mitad de los resultados a cada lado. En distribuciones asimétricas difiere de la media.'),
  GlossaryTerm('Asimetría', 'Falta de simetría: con cola derecha la media supera a la mediana.'),
  GlossaryTerm('Probabilidad del umbral', 'Fracción de iteraciones que cruzan un valor crítico (VAN < 0, plazo > contrato).'),
  GlossaryTerm('Valor en riesgo (VaR)', 'Percentil de la cola mala: por ejemplo, el P5 de la utilidad.'),
  GlossaryTerm('Déficit esperado', 'Promedio de los resultados de la cola mala (el 5 % peor): cuán malo es lo malo.'),
  GlossaryTerm('Regla del tres', 'Si un evento no aparece en n iteraciones, su probabilidad es menor que ≈ 3/n con 95 % de confianza.'),
  GlossaryTerm('Evento raro', 'Evento de probabilidad pequeña: su estimación requiere del orden de 100/p iteraciones para un error relativo del 10 %.'),
  GlossaryTerm('Análisis de sensibilidad', 'Medir cuánto contribuye cada entrada a la variabilidad de la salida.'),
  GlossaryTerm('Gráfico de tornado', 'Barras ordenadas por la influencia de cada entrada en la salida (aquí, correlación de rangos).'),
  GlossaryTerm('Correlación de Spearman', 'Correlación entre los rangos de dos variables; capta relaciones monótonas no lineales.'),
  GlossaryTerm('Validación del modelo', 'Comprobar que el modelo representa el sistema real: fórmula, supuestos y entradas. Es distinta de la precisión.'),
  GlossaryTerm('Reproducibilidad', 'Posibilidad de obtener exactamente el mismo resultado: requiere reportar generador, semilla y n.'),
];
